FROM node:20.17.0-alpine3.19

# Set the working directory
WORKDIR /app

# Install dependencies
COPY ./package.json .
COPY ./package-lock.json .
RUN npm install

# Copy all required files for the development environment
COPY ./tsconfig.json .
COPY ./public/ ./public/
COPY ./src/ ./src/
COPY ./.env ./.env

# Expose the development server on port 3000
EXPOSE 3000

# Run the development server on localhost
CMD ["npm", "run", "start"]
